// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4WVwS5RYswGvGZHvnj15jVMXE3fdm4yk',
    appId: '1:38535991187:web:a147f28c8e5b05f0936266',
    messagingSenderId: '38535991187',
    projectId: 'bookmet-c7831',
    authDomain: 'bookmet-c7831.firebaseapp.com',
    storageBucket: 'bookmet-c7831.firebasestorage.app',
    measurementId: 'G-Y5M0CJX0PT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAztobM4QMpuJRIY3DMp8hZUHJmLU-p_q8',
    appId: '1:38535991187:ios:efe1cadf4435605d936266',
    messagingSenderId: '38535991187',
    projectId: 'bookmet-c7831',
    storageBucket: 'bookmet-c7831.firebasestorage.app',
    iosClientId: '38535991187-srujpvurrn3tl9j386dipd4hp3vckm4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmet',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAztobM4QMpuJRIY3DMp8hZUHJmLU-p_q8',
    appId: '1:38535991187:ios:efe1cadf4435605d936266',
    messagingSenderId: '38535991187',
    projectId: 'bookmet-c7831',
    storageBucket: 'bookmet-c7831.firebasestorage.app',
    iosClientId: '38535991187-srujpvurrn3tl9j386dipd4hp3vckm4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmet',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAevu5XpAbayaSPzsIB_HXKAX4PVjmr--c',
    appId: '1:38535991187:android:73435d2f98c9d5d2936266',
    messagingSenderId: '38535991187',
    projectId: 'bookmet-c7831',
    storageBucket: 'bookmet-c7831.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4WVwS5RYswGvGZHvnj15jVMXE3fdm4yk',
    appId: '1:38535991187:web:dd1dde70c455ee5a936266',
    messagingSenderId: '38535991187',
    projectId: 'bookmet-c7831',
    authDomain: 'bookmet-c7831.firebaseapp.com',
    storageBucket: 'bookmet-c7831.firebasestorage.app',
    measurementId: 'G-LXBMJCX1DB',
  );

}